services:
  neo4j:
    image: neo4j:5.26-community
    container_name: vforensiq-neo4j
    ports:
      - "7474:7474"   # browser
      - "7687:7687"   # bolt
    environment:
      NEO4J_AUTH: "neo4j/vforensiq_dev"
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_dbms_memory_heap_initial__size: "512m"
      NEO4J_dbms_memory_heap_max__size: "1G"
    volumes:
      - neo4j-data:/data

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: vforensiq-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docs/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto-data:/mosquitto/data
    restart: unless-stopped

volumes:
  neo4j-data:
  mosquitto-data:
